language: node_js
before_install:
  - npm i lerna@2.0.0-beta.36 -g
  - npm i yarn -g
notifications:
  email: false
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - yarn
  - lerna bootstrap
script:
  - yarn lint
  - yarn test
